<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Products.aspx.cs" Inherits="Tuan2.Views.Products" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
  <p>
</p>
  <asp:GridView ID="gvProduct" runat="server" CellPadding="4" ForeColor="#333333" GridLines="Vertical" Height="217px" Width="650px" HorizontalAlign="Justify" BorderStyle="Solid" AutoGenerateDeleteButton="True">
  <AlternatingRowStyle BackColor="White" />
  <EditRowStyle BackColor="#7C6F57" />
  <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
  <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
  <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
  <RowStyle BackColor="#E3EAEB" />
  <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
  <SortedAscendingCellStyle BackColor="#F8FAFA" />
  <SortedAscendingHeaderStyle BackColor="#246B61" />
  <SortedDescendingCellStyle BackColor="#D4DFE1" />
  <SortedDescendingHeaderStyle BackColor="#15524A" />
</asp:GridView>
</asp:Content>
